name: CI

on:
  push:
    branches:
      - feature-githubactions

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 14, 16, 18, 22 ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: 'Setup node'
        uses: actions/setup-node@v4
        with: 
          node-version: ${{ matrix.node }}
      - name: Check version  
        run: node --version 

      - name: Install dependencies
        run: npm install

      - name: TypeScript Build Check
        run: npm run dev

      - name: Run tests
        run: npm test