name: CI

on:
  push:
    branches:
      - feature-githubactions

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.stats()'" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    strategy:
      matrix:
        node: [18, 20]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: npm install

      - name: Wait for MongoDB to be Ready
        run: sleep 10

      - name: TypeScript Build Check
        run: npx tsc --noEmit

      - name: Start Server in Background
        run: 
          npm run dev &
          sleep 5

      - name: Test Server Health
        run: curl http://localhost:3000/health

